---
- name: "terraform | check if tfenv repository has already existed"
  stat:
    path: "{{ tfenv_dir }}"
  register: chk_file

- name: "terraform | clone tfenv repository"
  git:
    repo: "https://github.com/tfutils/tfenv.git"
    dest: "{{ tfenv_dir }}"
  when: 
    - not chk_file.stat.exists

- name: "terraform | change file permissions"
  file:
    path: "{{ tfenv_dir }}"
    mode: '777'
    owner: "{{ terraform_user }}"
    group: "{{ terraform_user }}"
    recurse: yes

- name: "terraform | make symlink for {{ tfenv_dir }}/bin/terraform to /usr/local/bin/terraform"
  file:
    src: "{{ tfenv_dir }}/bin/terraform"
    dest: "/usr/local/bin/terraform"
    state: link

- name: "terraform | make symlink for {{ tfenv_dir }}/bin/tfenv to /usr/local/bin/tfenv"
  file:
    src: "{{ tfenv_dir }}/bin/tfenv"
    dest: "/usr/local/bin/tfenv"
    state: link
   
- name: "terraform | check if terraform {{ version }} has been already installed or not"
  shell: "tfenv list"
  register: register
  ignore_errors: true

- name: "terraform | install terraform {{ version}}"
  shell: "/usr/local/bin/tfenv install {{ version }}"
  when: "'{{ version }}' not in register.stdout"
  ignore_errors: true
